apiVersion: v1
kind: Service
metadata:
  name: maeno-frontend-service
  namespace: maeno-fe
spec:
  type: NodePort
  selector:
    role: maeno 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
