apiVersion: v1
kind: Service
metadata:
  name: maeno-backend-service
  namespace: maeno-be
spec:
  selector:
    role: maeno-backend-webserver 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
