apiVersion: v1
kind: Pod
metadata:
  name: share-logs
  namespace: scn-03
spec:
  containers:
  - image: busybox:latest
    name: c1
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /cache/exec.log; sleep 2;done"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: busybox:latest
    name: c2
    command: ["/bin/sh"]
    args: ["-c", "while true; do cp -f /cache/exec.log /data/exec.log; tail -n 1 /cache/exec.log; sleep 2;done"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    - mountPath: /data
      name: mounted-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  - name: mounted-volume
    hostPath:
      path: /production/maeno/volume
      type: Directory
